### ISSUE TITLE
INFOGRAFÍA - EDWIN LÓPEZ SANTIAGO

### ISSUE THREAD

**Issue by Edwin14459** [SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-Edwin14459#1]
[Infografía Gestión de Proyectos de Software - Edwin López Santiago.pdf](https://github.com/user-attachments/files/16770278/Infografia.Gestion.de.Proyectos.de.Software.-.Edwin.Lopez.Santiago.pdf)

**Comment by josealfredo79** [comment]
Calificacion 20 Bien hecho y revisado...
